### ISSUE TITLE
vreemde waarde in toelichting gezag niet te bepalen bij ontbrekend gegeven

### ISSUE THREAD

**Issue by fsamwel** [BRP-API/brp-api-gezag#135]
```
      Gegeven de persoon 'Henk' met burgerservicenummer '000000012'
      * is meerderjarig
      En de persoon 'Ingrid' met burgerservicenummer '000000024'
      * is meerderjarig
      En 'Henk' en 'Ingrid' zijn met elkaar gehuwd
      En de persoon 'Jaimy' met burgerservicenummer '000000036'
      * is ingeschreven in de BRP
      * is minderjarig
      * is in Nederland geboren
      * is niet geëmigreerd geweest
      * heeft 'Ingrid' als ouder 1
      Als gezag wordt gezocht met de volgende parameters
      | naam                | waarde    |
      | burgerservicenummer | 000000036 |
```
Dit geeft als antwoord:
```
{
       	"personen": [
       		{
       			"burgerservicenummer": "000000036",
       			"gezag": [
       				{
       					"type": "GezagNietTeBepalen",
       					"toelichting": "gezag is niet te bepalen omdat bij bepaling huwelijk/partnerschap relevante gegevens ontbreken. Het gaat om de volgende gegevens: c26ddb6b-5715-4e1b-8bc9-3fbe40aad3e3"
       				}
       			]
       		}
       	]
 }
```

Over welk gegeven gaat het dat hier ontbreekt?

N.B. om dit uit te voeren is automation in https://github.com/BRP-API/brp-api-gezag/pull/97 nodig

**Comment by FrozenSync** [comment]
Uitleg: er is een exception opgetreden waarbij een error trace code wordt gegenereerd. De placeholder is vervangen met deze error trace code in plaats van de missende gegeven.

**Comment by fsamwel** [comment]
dit issue is gevonden in #8 features/gezag-meerderjarige/gezamenlijk-gezag-kind-partner.feature:10. Wanneer vanuit de meerderjarige (partner van moeder) wordt gevraagd, krijg ik niet het verwachtte antwoord. Daarom getest wat er gebeurd wanneer gezag van de minderjarige direct wordt gevraagd, met bovenstaand resultaat

**Comment by fsamwel** [comment]
volgens de toelichting ontbreekt er iets aan de huwelijk/partnerschap gegevens.

Bij de moeder zijn de volgende relatiegegevens toegevoegd:
```
{
  text: 'INSERT INTO public.lo3_pl_persoon(pl_id,stapel_nr,volg_nr,persoon_type,burger_service_nr,geslachts_naam,relatie_start_datum,relatie_start_plaats,relatie_start_land_code) VALUES(
    '2',         '0',
    '0',         'R',
    '000000012', 'Henk',
    '20041016',  '0518',
    '6030'
)
```

welk gegeven ontbreekt hier?

**Comment by Patrick-4488** [comment]
De code kan niet overweg met het niet hebben van ouder2 bij het opvragen van aktenummers.
De gezagmodule probeerd om te bepalen of ouder2 ontkenning van ouderschap heeft gedaan.

Ik heb een nullcheck toegevoegd, daarmet is het probleem opgelost.

```
2024-10-21T12:29:24.457+02:00 ERROR 49160 --- [brp-api-gezag] [nio-8080-exec-3] n.r.m.g.s.gezagmodule.GezagBepaling      : Programmeerfout tijdens het bepalen van gezag (adc9853b-c8a2-4c4b-8fa7-f8400ee78653)

java.lang.NullPointerException: Cannot invoke "nl.rijksoverheid.mev.gezagsmodule.domain.Ouder2.getAktenummer()" because the return value of **"nl.rijksoverheid.mev.gezagsmodule.domain.Persoonslijst.getOuder2()" is null**
	at nl.rijksoverheid.mev.gezagsmodule.domain.Persoonslijst.ontkenningOuderschapDoorOuder2(Persoonslijst.java:459)
	at nl.rijksoverheid.mev.gezagsmodule.service.gezagmodule.IsStaandeHuwelijkOfPartnerschapGeboren.perform(IsStaandeHuwelijkOfPartnerschapGeboren.java:46)
```
